import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google';
import ToasterProvider from "../Providers/ToasterProvider";
import { Providers } from "../Providers/ClientProvider";
import Sidebar from "@/components/Sidebar";
import SignIn from "@/components/SignIn";

const inter = Inter({subsets:["latin"]});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <body
              className={`${inter.className} antialiased`}
              >
              <GoogleOAuthProvider clientId={process.env.clientId || ""}>
                <Providers>
                  <div className="grid grid-cols-12 w-full h-screen px-3 sm:px-6 md:px-10 2xl:px-28 bg-gray-950">
                    <div className="sm:col-span-3 col-span-2 flex flex-col">
                      <Sidebar/>
                    </div>
                    <div className="sm:col-span-5 col-span-10 sm:border-r-[1px] border-l-[1px] border-gray-700 h-screen overflow-y-scroll transition-all">
                      {children}
                    </div>
                    <div className="col-span-0 sm:col-span-3">
                      <SignIn/>
                    </div>
                  </div>
                  <ToasterProvider/>
                </Providers>
              </GoogleOAuthProvider>
            </body>
    </html>
  );
}